name: Dungeons
version: ${project.version}
main: github.dimazbtw.dungeons.Main
api-version: 1.20
depend: [cah-lib]
softdepend: [PlaceholderAPI]
authors: [dimazbtw]
description: Complete Dungeons System
